name: Build Android APK

on:
  push:
    branches: [ "main" ]

env:
  # यसले Node.js 24 को चेतावनीलाई हटाउँछ र नयाँ भर्सनमा चल्न मद्दत गर्छ
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer
          pip3 install --user --upgrade Cython==0.29.33

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          # यदि फाइल भेटिएन भने यहाँ स्पष्ट एरर म्यासेज देखिनेछ
          if [ ! -f buildozer.spec ]; then
            echo "ERROR: buildozer.spec file not found in the root directory!"
            exit 1
          fi
          buildozer android debug
